src/createAssistant.ts, src/typings.ts
<details>
<summary>📦 Published PR as canary version: <code>1.0.1--canary.1.128858c45774b1b1b2b8b8523d8aca3e90efb055.0</code></summary>
<br />
```bash
npm install @salutejs/client@1.0.1--canary.1.128858c45774b1b1b2b8b8523d8aca3e90efb055.0
yarn add @salutejs/client@1.0.1--canary.1.128858c45774b1b1b2b8b8523d8aca3e90efb055.0
```
</details>
=> Дженерики для SmartAppData

.github/workflows/release.yml, package-lock.json, package.json
<details>
<summary>📦 Published PR as canary version: <code>1.0.1--canary.6.3683d06106f9787e0c917621314907cbd1f8c8ab.0</code></summary>
<br />
```bash
npm install @salutejs/client@1.0.1--canary.6.3683d06106f9787e0c917621314907cbd1f8c8ab.0
yarn add @salutejs/client@1.0.1--canary.6.3683d06106f9787e0c917621314907cbd1f8c8ab.0
```
</details>
=> фикс экшенов

src/assistantSdk/assistant.ts, src/assistantSdk/client/client.ts, src/assistantSdk/client/protocol.ts, src/assistantSdk/voice/voice.ts
<details>
<summary>📦 Published PR as canary version: <code>1.0.1--canary.2.12ad9cef63bb7f98d4214dbd6de50e0b8339cd56.0</code></summary>
<br />
```bash
npm install @salutejs/client@1.0.1--canary.2.12ad9cef63bb7f98d4214dbd6de50e0b8339cd56.0
yarn add @salutejs/client@1.0.1--canary.2.12ad9cef63bb7f98d4214dbd6de50e0b8339cd56.0
```
</details>
=> fix: Теперь при отключении озвучки в момент слушания случайная смена эмоции не произойдёт

cypress/integration/createAssistant.spec.ts, global.d.ts, src/appInitialData.ts, src/createAssistant.ts
<details>
<summary>📦 Published PR as canary version: <code>1.2.0--canary.13.e99cb6010bee8c009b7959d4722d0ffce5108b62.0</code></summary>
<br />
```bash
npm install @salutejs/client@1.2.0--canary.13.e99cb6010bee8c009b7959d4722d0ffce5108b62.0
yarn add @salutejs/client@1.2.0--canary.13.e99cb6010bee8c009b7959d4722d0ffce5108b62.0
```
</details>
=> feat: Добавлено поле firstMessageId в window.__ASSISTANT_CLIENT__

package-lock.json, package.json
<details>
<summary>📦 Published PR as canary version: <code>1.2.0--canary.9.6778a2c9d8b7ebcc965ea11dc5a5904bcf3d4038.0</code></summary>
<br />
```bash
npm install @salutejs/client@1.2.0--canary.9.6778a2c9d8b7ebcc965ea11dc5a5904bcf3d4038.0
yarn add @salutejs/client@1.2.0--canary.9.6778a2c9d8b7ebcc965ea11dc5a5904bcf3d4038.0
```
</details>
=> feat: Обновлена версия Scenario

src/assistantSdk/assistant.ts, src/assistantSdk/client/client.ts, src/assistantSdk/client/methods.ts, src/assistantSdk/client/protocol.ts, src/proto/index.d.ts, src/proto/index.js, src/proto/index.proto, src/typings.ts
<details>
<summary>📦 Published PR as canary version: <code>1.4.0--canary.4.00118464d6afa33c6f78abaa0b56d7008a1da996.0</code></summary>
<br />
```bash
npm install @salutejs/client@1.4.0--canary.4.00118464d6afa33c6f78abaa0b56d7008a1da996.0
yarn add @salutejs/client@1.4.0--canary.4.00118464d6afa33c6f78abaa0b56d7008a1da996.0
```
</details>
=> Добавлена поддержка GetHistoryRequest

src/typings.ts
<details>
<summary>📦 Published PR as canary version: <code>1.4.1--canary.16.ad6073f5703fdf214d85408a190a92c65fcc3562.0</code></summary>
<br />
```bash
npm install @salutejs/client@1.4.1--canary.16.ad6073f5703fdf214d85408a190a92c65fcc3562.0
yarn add @salutejs/client@1.4.1--canary.16.ad6073f5703fdf214d85408a190a92c65fcc3562.0
```
</details>
=> fix: Исправлены типы для GetHistoryRequset

src/assistantSdk/assistant.ts
<details>
<summary>📦 Published PR as canary version: <code>1.4.2--canary.22.496f90f3e633ad6af45ad00d5366dfc60931b699.0</code></summary>
<br />
```bash
npm install @salutejs/client@1.4.2--canary.22.496f90f3e633ad6af45ad00d5366dfc60931b699.0
yarn add @salutejs/client@1.4.2--canary.22.496f90f3e633ad6af45ad00d5366dfc60931b699.0
```
</details>
=> fix: Теперь после command.type === action обработка items не прерывается

README.md, src/assistantSdk/assistant.ts, src/assistantSdk/voice/player/trackStream.ts, src/assistantSdk/voice/voice.ts, src/createAssistant.ts, src/dev.ts, src/typings.ts
<details>
<summary>📦 Published PR as canary version: <code>1.5.0--canary.24.b816d923a256a806c6540014509311765c560f66.0</code></summary>
<br />
```bash
npm install @salutejs/client@1.5.0--canary.24.b816d923a256a806c6540014509311765c560f66.0
yarn add @salutejs/client@1.5.0--canary.24.b816d923a256a806c6540014509311765c560f66.0
```
</details>
=> Подписка на события озвучки

README.md
<details>
<summary>📦 Published PR as canary version: <code>1.5.1--canary.25.33c4c39ea7143b10c2ae3db49ba0f019e09403ef.0</code></summary>
<br />
```bash
npm install @salutejs/client@1.5.1--canary.25.33c4c39ea7143b10c2ae3db49ba0f019e09403ef.0
yarn add @salutejs/client@1.5.1--canary.25.33c4c39ea7143b10c2ae3db49ba0f019e09403ef.0
```
</details>
=> Cсылки на stable-пакеты

cypress/integration/createAssistantDev.spec.ts, cypress/integration/greetings.spec.ts, cypress/integration/initializeAssistantSDK.spec.ts, cypress/integration/requestPermissions.spec.ts, src/assistantSdk/assistant.ts, src/assistantSdk/client/client.ts, src/assistantSdk/meta.ts, src/typings.ts
<details>
<summary>📦 Published PR as canary version: <code>1.6.0--canary.30.b295733a6872f40c34fa044f4e2016cf982da38d.0</code></summary>
<br />
```bash
npm install @salutejs/client@1.6.0--canary.30.b295733a6872f40c34fa044f4e2016cf982da38d.0
yarn add @salutejs/client@1.6.0--canary.30.b295733a6872f40c34fa044f4e2016cf982da38d.0
```
</details>
=> Отправка меты вне SystemMessage

src/assistantSdk/voice/player/trackStream.ts, src/assistantSdk/voice/voice.ts
<details>
<summary>📦 Published PR as canary version: <code>1.6.1--canary.33.3695bffddb885366b942570d4c66903bcaeefa2f.0</code></summary>
<br />
```bash
npm install @salutejs/client@1.6.1--canary.33.3695bffddb885366b942570d4c66903bcaeefa2f.0
yarn add @salutejs/client@1.6.1--canary.33.3695bffddb885366b942570d4c66903bcaeefa2f.0
```
</details>
=> Зависание озвучки

cypress.json, src/assistantSdk/assistant.ts, src/assistantSdk/client/protocol.ts, src/assistantSdk/client/transport.spec.ts, src/assistantSdk/client/transport.ts, src/assistantSdk/client/types.ts, tsconfig.json
<details>
<summary>📦 Published PR as canary version: <code>1.6.2--canary.37.8517e37e0c91a35192a0193fe31b57b32b239e50.0</code></summary>
<br />
```bash
npm install @salutejs/client@1.6.2--canary.37.8517e37e0c91a35192a0193fe31b57b32b239e50.0
yarn add @salutejs/client@1.6.2--canary.37.8517e37e0c91a35192a0193fe31b57b32b239e50.0
```
</details>
=> fix: Исправлено бесконечное слушание в оффлайн-режиме

src/assistantSdk/client/protocol.ts
<details>
<summary>📦 Published PR as canary version: <code>1.6.3--canary.40.c027141364e7ee14321e8bcb5628ecba1908c61f.0</code></summary>
<br />
```bash
npm install @salutejs/client@1.6.3--canary.40.c027141364e7ee14321e8bcb5628ecba1908c61f.0
yarn add @salutejs/client@1.6.3--canary.40.c027141364e7ee14321e8bcb5628ecba1908c61f.0
```
</details>
=> Исправлен бесконечный реконнект при невалидном токене

README.md, src/appInitialData.ts, src/typings.ts
<details>
<summary>📦 Published PR as canary version: <code>1.7.0--canary.38.f801afb1a0b2ea5070d6322cbc4a1b0449f73673.0</code></summary>
<br />
```bash
npm install @salutejs/client@1.7.0--canary.38.f801afb1a0b2ea5070d6322cbc4a1b0449f73673.0
yarn add @salutejs/client@1.7.0--canary.38.f801afb1a0b2ea5070d6322cbc4a1b0449f73673.0
```
</details>
=> feat: Добавлена поддержка static insets

src/createAssistantDev.ts, src/typings.ts
Closes #47 
<details>
<summary>📦 Published PR as canary version: <code>1.7.1--canary.49.f70639b83828e46553b52f7cb6dbb831ca91487a.0</code></summary>
<br />
```bash
npm install @salutejs/client@1.7.1--canary.49.f70639b83828e46553b52f7cb6dbb831ca91487a.0
yarn add @salutejs/client@1.7.1--canary.49.f70639b83828e46553b52f7cb6dbb831ca91487a.0
```
</details>
=> Актуализация типа AppContext

src/assistantSdk/assistant.ts, src/typings.ts
<details>
<summary>📦 Published PR as canary version: <code>1.8.0--canary.50.9edb867978eaae0409a78209b7ce148178377b90.0</code></summary>
<br />
```bash
npm install @salutejs/client@1.8.0--canary.50.9edb867978eaae0409a78209b7ce148178377b90.0
yarn add @salutejs/client@1.8.0--canary.50.9edb867978eaae0409a78209b7ce148178377b90.0
```
</details>
=> feat: Добавлено хранилище sdkMeta. Добавлена отправка текущей темы в VPS

src/assistantSdk/assistant.ts, src/assistantSdk/client/protocol.ts, src/assistantSdk/client/transport.spec.ts, src/assistantSdk/client/transport.ts, src/assistantSdk/client/types.ts
<details>
<summary>📦 Published PR as canary version: <code>1.8.1--canary.42.8a0f858a396000e457fa7c8551f7b682f105c4fd.0</code></summary>
<br />
```bash
npm install @salutejs/client@1.8.1--canary.42.8a0f858a396000e457fa7c8551f7b682f105c4fd.0
yarn add @salutejs/client@1.8.1--canary.42.8a0f858a396000e457fa7c8551f7b682f105c4fd.0
```
</details>
=> fix: Исправлен множественный вызов transport.open()

README.md
<details>
<summary>📦 Published PR as canary version: <code>1.8.3--canary.57.f2d7aabee19532ee901d3e81913d21c3ebe9fce1.0</code></summary>
<br />
```bash
npm install @salutejs/client@1.8.3--canary.57.f2d7aabee19532ee901d3e81913d21c3ebe9fce1.0
yarn add @salutejs/client@1.8.3--canary.57.f2d7aabee19532ee901d3e81913d21c3ebe9fce1.0
```
</details>
=> Добавлено описание AssistantVisibilityCommand

cypress/integration/createAssistant.spec.ts, src/createAssistant.ts, src/dev.ts, src/mock.ts, src/typings.ts
<details>
<summary>📦 Published PR as canary version: <code>1.9.0--canary.55.3171e9dfb0ba346aebc3c14170880b462d71c739.0</code></summary>
<br />
```bash
npm install @salutejs/client@1.9.0--canary.55.3171e9dfb0ba346aebc3c14170880b462d71c739.0
yarn add @salutejs/client@1.9.0--canary.55.3171e9dfb0ba346aebc3c14170880b462d71c739.0
```
</details>
=> feat: добавил setHeaderButtons в AssistantHost

package-lock.json, package.json
<details>
<summary>📦 Published PR as canary version: <code>1.9.1--canary.59.ce58eb57c16bed8b0a616da21960bd5f2f76c00a.0</code></summary>
<br />
```bash
npm install @salutejs/client@1.9.1--canary.59.ce58eb57c16bed8b0a616da21960bd5f2f76c00a.0
yarn add @salutejs/client@1.9.1--canary.59.ce58eb57c16bed8b0a616da21960bd5f2f76c00a.0
```
</details>
=> fix: Актуализация @salutejs/scenario

package-lock.json, package.json, src/typings.ts
<details>
<summary>📦 Published PR as canary version: <code>1.9.2--canary.60.e8e5f2f894a26eba1febf0d9a0d8e284e10e3f21.0</code></summary>
<br />
```bash
npm install @salutejs/client@1.9.2--canary.60.e8e5f2f894a26eba1febf0d9a0d8e284e10e3f21.0
yarn add @salutejs/client@1.9.2--canary.60.e8e5f2f894a26eba1febf0d9a0d8e284e10e3f21.0
```
</details>
=> fix: Добавлен ExtendedListCard в SystemMessage

src/createAssistantDev.ts
<details>
<summary>📦 Published PR as canary version: <code>1.9.3--canary.62.8a30cd8be9cee06b7b00032217304c7abc180ffc.0</code></summary>
<br />
```bash
npm install @salutejs/client@1.9.3--canary.62.8a30cd8be9cee06b7b00032217304c7abc180ffc.0
yarn add @salutejs/client@1.9.3--canary.62.8a30cd8be9cee06b7b00032217304c7abc180ffc.0
```
</details>
=> обновлен хост платформы

cypress/integration/initializeAssistantSDK.spec.ts, src/assistantSdk/assistant.ts, src/assistantSdk/client/client.ts, src/assistantSdk/client/methods.ts, src/assistantSdk/client/protocol.ts, src/typings.ts
<details>
<summary>📦 Published PR as canary version: <code>1.10.0--canary.52.ae04ec395096503de20e27ed62a112320c87a77c.0</code></summary>
<br />
```bash
npm install @salutejs/client@1.10.0--canary.52.ae04ec395096503de20e27ed62a112320c87a77c.0
yarn add @salutejs/client@1.10.0--canary.52.ae04ec395096503de20e27ed62a112320c87a77c.0
```
</details>
=> feat: Убрана отправка меты в легаси-формате

cypress/integration/changeSettings.spec.ts, cypress/integration/listen.spec.ts, cypress/support/helpers/clientMethods.helpers.ts, src/assistantSdk/assistant.ts, src/assistantSdk/mutexSwitcher.ts, src/assistantSdk/mutexedObject.ts, src/assistantSdk/voice/listener/voiceListener.ts, src/assistantSdk/voice/voice.ts
<details>
<summary>📦 Published PR as canary version: <code>1.11.0--canary.61.57080dafb0548901524a99b7d57a2729ca9bab4e.0</code></summary>
<br />
```bash
npm install @salutejs/client@1.11.0--canary.61.57080dafb0548901524a99b7d57a2729ca9bab4e.0
yarn add @salutejs/client@1.11.0--canary.61.57080dafb0548901524a99b7d57a2729ca9bab4e.0
```
</details>
=> feat: Добавлен интерфейс для assistant.settings

README.md, cypress/integration/createAssistant.spec.ts, src/createAssistant.ts
<details>
<summary>📦 Published PR as canary version: <code>1.12.0--canary.65.e9684b17f8b6d7a02f81b6c485c6a993a2ccb165.0</code></summary>
<br />
```bash
npm install @salutejs/client@1.12.0--canary.65.e9684b17f8b6d7a02f81b6c485c6a993a2ccb165.0
yarn add @salutejs/client@1.12.0--canary.65.e9684b17f8b6d7a02f81b6c485c6a993a2ccb165.0
```
</details>
=> fix: Добавлено прокидывание ответов sendAction в emitCommand

README.md, src/appInitialData.ts, src/createAssistant.ts
<details>
<summary>📦 Published PR as canary version: <code>1.13.0--canary.66.995f816f999c3dcb8964172162c8fa5efbc28102.0</code></summary>
<br />
```bash
npm install @salutejs/client@1.13.0--canary.66.995f816f999c3dcb8964172162c8fa5efbc28102.0
yarn add @salutejs/client@1.13.0--canary.66.995f816f999c3dcb8964172162c8fa5efbc28102.0
```
</details>
=> feat: Добавлена возможность подписаться на конкретную команду

cypress/integration/autolistening.spec.ts, cypress/integration/createAssistantDev.spec.ts, cypress/integration/listen.spec.ts, cypress/support/helpers/clientMethods.helpers.ts, src/assistantSdk/assistant.ts, src/assistantSdk/voice/voice.ts
<details>
<summary>📦 Published PR as canary version: <code>1.13.3--canary.73.4d9ab4522304365655bd3971a89e8117de1c3758.0</code></summary>
<br />
```bash
npm install @salutejs/client@1.13.3--canary.73.4d9ab4522304365655bd3971a89e8117de1c3758.0
yarn add @salutejs/client@1.13.3--canary.73.4d9ab4522304365655bd3971a89e8117de1c3758.0
```
</details>
=> fix: Добавлены тесты автослушания

cypress/integration/connection.spec.ts
<details>
<summary>📦 Published PR as canary version: <code>1.13.3--canary.75.f42c9360a8b6bc2a5ce63a1138b56f019db2568a.0</code></summary>
<br />
```bash
npm install @salutejs/client@1.13.3--canary.75.f42c9360a8b6bc2a5ce63a1138b56f019db2568a.0
yarn add @salutejs/client@1.13.3--canary.75.f42c9360a8b6bc2a5ce63a1138b56f019db2568a.0
```
</details>
=> test: Добавлены тесты переподключения к сокету

cypress/integration/autolistening.spec.ts, cypress/integration/backgroundApps.spec.ts, cypress/integration/changeSettings.spec.ts, cypress/integration/connection.spec.ts, cypress/integration/disableDubbing.spec.ts, cypress/integration/greetings.spec.ts, cypress/integration/listen.spec.ts, cypress/integration/refreshToken.spec.ts, cypress/integration/requestPermissions.spec.ts, cypress/support/helpers/init.ts
<details>
<summary>📦 Published PR as canary version: <code>1.13.4--canary.77.faedbb35194c72c8a0f31b0b2927117622dce4b3.0</code></summary>
<br />
```bash
npm install @salutejs/client@1.13.4--canary.77.faedbb35194c72c8a0f31b0b2927117622dce4b3.0
yarn add @salutejs/client@1.13.4--canary.77.faedbb35194c72c8a0f31b0b2927117622dce4b3.0
```
</details>
=> test: Добавлены тесты для backgroundApps

cypress/integration/disableDubbing.spec.ts, cypress/support/helpers/clientMethods.helpers.ts, src/assistantSdk/assistant.ts, src/assistantSdk/mutexSwitcher.ts, src/assistantSdk/voice/voice.ts
<details>
<summary>📦 Published PR as canary version: <code>1.13.4--canary.69.0fc47bcf7145354a2b61a9be259373d36ed591ee.0</code></summary>
<br />
```bash
npm install @salutejs/client@1.13.4--canary.69.0fc47bcf7145354a2b61a9be259373d36ed591ee.0
yarn add @salutejs/client@1.13.4--canary.69.0fc47bcf7145354a2b61a9be259373d36ed591ee.0
```
</details>
=> fix: Добавлены тесты для методов sendText changeSettings stopVoice

src/assistantSdk/assistant.ts
<details>
<summary>📦 Published PR as canary version: <code>1.13.5--canary.84.46ea19d87bdb79185d152d1b27045905c7502139.0</code></summary>
<br />
```bash
npm install @salutejs/client@1.13.5--canary.84.46ea19d87bdb79185d152d1b27045905c7502139.0
yarn add @salutejs/client@1.13.5--canary.84.46ea19d87bdb79185d152d1b27045905c7502139.0
```
</details>
=> fix: убрал прерывание озвучки и слушания в sendServerAction

cypress/integration/createAssistantDev.spec.ts, src/dev.ts
Closes #56 
<details>
<summary>📦 Published PR as canary version: <code>1.13.6--canary.83.db58036718b9706ba9103a893ad31c8ec7f0f9e8.0</code></summary>
<br />
```bash
npm install @salutejs/client@1.13.6--canary.83.db58036718b9706ba9103a893ad31c8ec7f0f9e8.0
yarn add @salutejs/client@1.13.6--canary.83.db58036718b9706ba9103a893ad31c8ec7f0f9e8.0
```
</details>
=> fix: Отключена отправка приветствия для канвасов

cypress/integration/backgroundApps.spec.ts, cypress/integration/meta.spec.ts, cypress/support/commands.ts, cypress/support/index.ts, src/assistantSdk/assistant.ts, src/assistantSdk/client/client.ts, src/assistantSdk/client/protocol.ts, src/typings.ts
<details>
<summary>📦 Published PR as canary version: <code>1.16.0--canary.88.4676071966.0</code></summary>
<br />
```bash
npm install @salutejs/client@1.16.0--canary.88.4676071966.0
yarn add @salutejs/client@1.16.0--canary.88.4676071966.0
```
</details>
=> Отправлять мету в первом сообщении

cypress/integration/connection.spec.ts, src/assistantSdk/assistant.ts, src/assistantSdk/client/protocol.ts
<details>
<summary>📦 Published PR as canary version: <code>1.16.2--canary.91.c26994ea230dcf1d7d6654f919f5c984266ab92a.0</code></summary>
<br />
```bash
npm install @salutejs/client@1.16.2--canary.91.c26994ea230dcf1d7d6654f919f5c984266ab92a.0
yarn add @salutejs/client@1.16.2--canary.91.c26994ea230dcf1d7d6654f919f5c984266ab92a.0
```
</details>
=> fix: экспорт assistant.status

src/assistantSdk/assistant.ts, src/assistantSdk/client/client.ts, src/assistantSdk/voice/voice.ts, src/typings.ts
<details>
<summary>📦 Published PR as canary version: <code>1.17.2--canary.95.ae4cb6bb9589d2627f976a43946e093e5bde810b.0</code></summary>
<br />
```bash
npm install @salutejs/client@1.17.2--canary.95.ae4cb6bb9589d2627f976a43946e093e5bde810b.0
yarn add @salutejs/client@1.17.2--canary.95.ae4cb6bb9589d2627f976a43946e093e5bde810b.0
```
</details>
=> fix: добавил source в мету

src/assistantSdk/voice/listener/navigatorAudioProvider.ts
<details>
<summary>📦 Published PR as canary version: <code>1.17.3--canary.98.834e30e15aee93f564264e5bff69e583b61769ea.0</code></summary>
<br />
```bash
npm install @salutejs/client@1.17.3--canary.98.834e30e15aee93f564264e5bff69e583b61769ea.0
yarn add @salutejs/client@1.17.3--canary.98.834e30e15aee93f564264e5bff69e583b61769ea.0
```
</details>
=> fix: Корректная обработка ошибки доступа к микро

src/assistantSdk/assistant.ts, src/index.ts
<details>
<summary>📦 Published PR as canary version: <code>1.17.3--canary.97.cc3cc62d2a2b75fb9d82958e7b09e8d7fc211de8.0</code></summary>
<br />
```bash
npm install @salutejs/client@1.17.3--canary.97.cc3cc62d2a2b75fb9d82958e7b09e8d7fc211de8.0
yarn add @salutejs/client@1.17.3--canary.97.cc3cc62d2a2b75fb9d82958e7b09e8d7fc211de8.0
```
</details>
=> chore: Экспортированы некоторые методы protobuf

src/assistantSdk/assistant.ts, src/assistantSdk/client/client.ts, src/assistantSdk/client/protocol.ts, src/typings.ts
<details>
<summary>📦 Published PR as canary version: <code>1.20.0--canary.106.72b9aef034fbd95dbea49cacefcb13a96d82d760.0</code></summary>
<br />
```bash
npm install @salutejs/client@1.20.0--canary.106.72b9aef034fbd95dbea49cacefcb13a96d82d760.0
yarn add @salutejs/client@1.20.0--canary.106.72b9aef034fbd95dbea49cacefcb13a96d82d760.0
```
</details>
=> Не отправлять чанки до установки соединения

src/createAssistant.ts
<details>
<summary>📦 Published PR as canary version: <code>1.21.0--canary.105.7a92c8e10f825fa2f48271b08ad65b0364686f57.0</code></summary>
<br />
```bash
npm install @salutejs/client@1.21.0--canary.105.7a92c8e10f825fa2f48271b08ad65b0364686f57.0
yarn add @salutejs/client@1.21.0--canary.105.7a92c8e10f825fa2f48271b08ad65b0364686f57.0
```
</details>
=> feat: Добавлено сообщение о канарейке

src/assistantSdk/voice/listener/navigatorAudioProvider.ts, src/assistantSdk/voice/listener/voiceListener.ts, src/assistantSdk/voice/recognizers/speechRecognizer.ts, src/assistantSdk/voice/voice.ts
<details>
<summary>📦 Published PR as canary version: <code>1.20.1--canary.108.9f99a400fd0bb1a3c47126af0ae27bd2b179ffcf.0</code></summary>
<br />
```bash
npm install @salutejs/client@1.20.1--canary.108.9f99a400fd0bb1a3c47126af0ae27bd2b179ffcf.0
yarn add @salutejs/client@1.20.1--canary.108.9f99a400fd0bb1a3c47126af0ae27bd2b179ffcf.0
```
</details>
=> fix: Останавливать слушание после assistant.stop

src/assistantSdk/assistant.ts
<details>
<summary>📦 Published PR as canary version: <code>1.21.3--canary.112.834c9a9f3fd56f6a15abdd28a314bdcc8dba9f53.0</code></summary>
<br />
```bash
npm install @salutejs/client@1.21.3--canary.112.834c9a9f3fd56f6a15abdd28a314bdcc8dba9f53.0
yarn add @salutejs/client@1.21.3--canary.112.834c9a9f3fd56f6a15abdd28a314bdcc8dba9f53.0
```
</details>
=> Игнорировать activate_app_info для чатаппов

.github/workflows/semgrep.yml
<details>
<summary>📦 Published PR as canary version: <code>1.21.4--canary.129.ebba43eff954d3195dc30ce662bbc977c565f9ed.0</code></summary>
<br />
```bash
npm install @salutejs/client@1.21.4--canary.129.ebba43eff954d3195dc30ce662bbc977c565f9ed.0
yarn add @salutejs/client@1.21.4--canary.129.ebba43eff954d3195dc30ce662bbc977c565f9ed.0
```
</details>
=> chore: semgrep

.github/workflows/semgrep.yml
<details>
<summary>📦 Published PR as canary version: <code>1.21.4--canary.130.ffd1d78c581b050a274e039fac4401d15e745f81.0</code></summary>
<br />
```bash
npm install @salutejs/client@1.21.4--canary.130.ffd1d78c581b050a274e039fac4401d15e745f81.0
yarn add @salutejs/client@1.21.4--canary.130.ffd1d78c581b050a274e039fac4401d15e745f81.0
```
</details>
=> chore: обновленный конфиг semgrep

.gitignore, cypress/integration/createAssistant.spec.ts, cypress/integration/createAssistantDev.spec.ts, cypress/integration/createAssistantWeb.spec.ts, cypress/integration/initializeAssistantSDK.spec.ts, cypress/integration/sendAction.spec.ts, cypress/plugins/index.js, cypress/support/helpers/init.ts, cypress/support/index.ts, package-lock.json, package.json
<details>
<summary>📦 Published PR as canary version: <code>1.21.4--canary.114.1facabbacf3d4e5f2324ed2eda23120844e6f7c2.0</code></summary>
<br />
```bash
npm install @salutejs/client@1.21.4--canary.114.1facabbacf3d4e5f2324ed2eda23120844e6f7c2.0
yarn add @salutejs/client@1.21.4--canary.114.1facabbacf3d4e5f2324ed2eda23120844e6f7c2.0
```
</details>
=> Тесты на готовой esm-сборке

cypress/integration/connection.spec.ts, cypress/support/websocketMock.ts
<details>
<summary>📦 Published PR as canary version: <code>1.21.4--canary.133.5711f4065b0c8045a0550080320106714782be80.0</code></summary>
<br />
```bash
npm install @salutejs/client@1.21.4--canary.133.5711f4065b0c8045a0550080320106714782be80.0
yarn add @salutejs/client@1.21.4--canary.133.5711f4065b0c8045a0550080320106714782be80.0
```
</details>
=> test: Тесты api reconnect

package-lock.json, package.json, rollup.config.js
closes #134 
<details>
<summary>📦 Published PR as canary version: <code>1.21.4--canary.135.42908a1a2838ac8db037083542c042cdc6ec647c.0</code></summary>
<br />
```bash
npm install @salutejs/client@1.21.4--canary.135.42908a1a2838ac8db037083542c042cdc6ec647c.0
yarn add @salutejs/client@1.21.4--canary.135.42908a1a2838ac8db037083542c042cdc6ec647c.0
```
</details>
=> в бандл сдк не должен попадать record

src/createAssistantDevOrigin.ts
closes #137 
<details>
<summary>📦 Published PR as canary version: <code>1.21.5--canary.138.5b4d9b02bf439c508d898d1d2df2f28bc464ddc9.0</code></summary>
<br />
```bash
npm install @salutejs/client@1.21.5--canary.138.5b4d9b02bf439c508d898d1d2df2f28bc464ddc9.0
yarn add @salutejs/client@1.21.5--canary.138.5b4d9b02bf439c508d898d1d2df2f28bc464ddc9.0
```
</details>
=> fix: Поменять адрес точки подключения в dev-режиме

src/createAssistantDev.ts
<details>
<summary>📦 Published PR as canary version: <code>1.22.1--canary.142.6f6d46d7c752f29a9ad68ee0102da3e605c7ce72.0</code></summary>
<br />
```bash
npm install @salutejs/client@1.22.1--canary.142.6f6d46d7c752f29a9ad68ee0102da3e605c7ce72.0
yarn add @salutejs/client@1.22.1--canary.142.6f6d46d7c752f29a9ad68ee0102da3e605c7ce72.0
```
</details>
=> fix: Исправлены типы динамического экспорта

src/createAssistant.ts, src/createAssistantDevOrigin.ts, src/dev.ts, src/typings.ts
<details>
<summary>📦 Published PR as canary version: <code>1.23.0--canary.144.77efc0d85179e3e9c07b4319a37448ebbbac2c09.0</code></summary>
<br />
```bash
npm install @salutejs/client@1.23.0--canary.144.77efc0d85179e3e9c07b4319a37448ebbbac2c09.0
yarn add @salutejs/client@1.23.0--canary.144.77efc0d85179e3e9c07b4319a37448ebbbac2c09.0
```
</details>
=> Поддержка геолокации

cypress/integration/createAssistant.spec.ts, src/createAssistant.ts, src/typings.ts
<details>
<summary>📦 Published PR as canary version: <code>1.23.1--canary.145.a16747422374742ba5bebf3f628cc642c60dddf2.0</code></summary>
<br />
```bash
npm install @salutejs/client@1.23.1--canary.145.a16747422374742ba5bebf3f628cc642c60dddf2.0
yarn add @salutejs/client@1.23.1--canary.145.a16747422374742ba5bebf3f628cc642c60dddf2.0
```
</details>
=> Не сериализовывать кнопки для хидера

README.md, src/assistantSdk/assistant.ts, src/assistantSdk/client/client.ts, src/createAssistant.ts, src/dev.ts, src/typings.ts
<details>
<summary>📦 Published PR as canary version: <code>1.24.0--canary.148.31e339df36d1af234541f185437e1a54864695b2.0</code></summary>
<br />
```bash
npm install @salutejs/client@1.24.0--canary.148.31e339df36d1af234541f185437e1a54864695b2.0
yarn add @salutejs/client@1.24.0--canary.148.31e339df36d1af234541f185437e1a54864695b2.0
```
</details>
=> feat: Возможность передавать mode для server_action

.github/workflows/release.yml
<details>
<summary>📦 Published PR as canary version: <code>1.24.2--canary.151.d0a492542065d51611c74a1f1faf80c5ef369582.0</code></summary>
<br />
```bash
npm install @salutejs/client@1.24.2--canary.151.d0a492542065d51611c74a1f1faf80c5ef369582.0
yarn add @salutejs/client@1.24.2--canary.151.d0a492542065d51611c74a1f1faf80c5ef369582.0
```
</details>
=> build: отключены тесты

cypress/integration/greetings.spec.ts
<details>
<summary>📦 Published PR as canary version: <code>1.24.3--canary.153.70842b8d6bc1638c6cff6bca3b00a1bf2d868903.0</code></summary>
<br />
```bash
npm install @salutejs/client@1.24.3--canary.153.70842b8d6bc1638c6cff6bca3b00a1bf2d868903.0
yarn add @salutejs/client@1.24.3--canary.153.70842b8d6bc1638c6cff6bca3b00a1bf2d868903.0
```
</details>
=> test: Добавлен тест для OPEN_ASSISTANT при sendText

cypress/integration/createAssistantDev.spec.ts, cypress/support/helpers/socket.ts, src/dev.ts, src/typings.ts
<details>
<summary>📦 Published PR as canary version: <code>1.25.0--canary.158.abd610486508a04169ee194a9a79800f275e3931.0</code></summary>
<br />
```bash
npm install @salutejs/client@1.25.0--canary.158.abd610486508a04169ee194a9a79800f275e3931.0
yarn add @salutejs/client@1.25.0--canary.158.abd610486508a04169ee194a9a79800f275e3931.0
```
</details>
=> feat: формировать feature_laucher в appInitialData

src/dev.ts
<details>
<summary>📦 Published PR as canary version: <code>1.26.0--canary.156.c396bb0d1d6413ccc308907d0ef2b7bca39458ef.0</code></summary>
<br />
```bash
npm install @salutejs/client@1.26.0--canary.156.c396bb0d1d6413ccc308907d0ef2b7bca39458ef.0
yarn add @salutejs/client@1.26.0--canary.156.c396bb0d1d6413ccc308907d0ef2b7bca39458ef.0
```
</details>
=> feat: Добавлен выброс ошибки для незарегистрированных навыков

src/assistantSdk/voice/audioContext.ts
<details>
<summary>📦 Published PR as canary version: <code>1.26.2--canary.161.1f7f119f2cdb5c44d64b4689d70579dd3dd30a71.0</code></summary>
<br />
```bash
npm install @salutejs/client@1.26.2--canary.161.1f7f119f2cdb5c44d64b4689d70579dd3dd30a71.0
yarn add @salutejs/client@1.26.2--canary.161.1f7f119f2cdb5c44d64b4689d70579dd3dd30a71.0
```
</details>
=> fix: воспроизведение озвучки на ios

src/assistantSdk/voice/audioContext.ts
<details>
<summary>📦 Published PR as canary version: <code>1.26.3--canary.162.8ed8ace4bb9f57d559c37d32e112355258b3fd96.0</code></summary>
<br />
```bash
npm install @salutejs/client@1.26.3--canary.162.8ed8ace4bb9f57d559c37d32e112355258b3fd96.0
yarn add @salutejs/client@1.26.3--canary.162.8ed8ace4bb9f57d559c37d32e112355258b3fd96.0
```
</details>
=> chore: отписка от touchstart

cypress/integration/dubbing.spec.ts, src/assistantSdk/voice/player/trackStream.ts, src/assistantSdk/voice/player/voicePlayer.ts, src/assistantSdk/voice/voice.ts
<details>
<summary>📦 Published PR as canary version: <code>1.27.0--canary.165.ce6badb360a0d03a7d56971542455e38cbf8a48a.0</code></summary>
<br />
```bash
npm install @salutejs/client@1.27.0--canary.165.ce6badb360a0d03a7d56971542455e38cbf8a48a.0
yarn add @salutejs/client@1.27.0--canary.165.ce6badb360a0d03a7d56971542455e38cbf8a48a.0
```
</details>
=> feat: Добавлена отправка cancel при принудительной остановке озвучки

src/assistantSdk/assistant.ts, src/assistantSdk/voice/recognizers/musicRecognizer.ts, src/assistantSdk/voice/voice.ts
<details>
<summary>📦 Published PR as canary version: <code>1.27.0--canary.163.0669e03d23628caf5bf32d0b7e043fd9bbf29699.0</code></summary>
<br />
```bash
npm install @salutejs/client@1.27.0--canary.163.0669e03d23628caf5bf32d0b7e043fd9bbf29699.0
yarn add @salutejs/client@1.27.0--canary.163.0669e03d23628caf5bf32d0b7e043fd9bbf29699.0
```
</details>
=> feat: расширенные статусы слушания

cypress/integration/listen.spec.ts, cypress/support/helpers/clientMethods.ts, cypress/support/proto/asr.d.ts, cypress/support/proto/asr.js, cypress/support/proto/mtt.d.ts, cypress/support/proto/mtt.js, package.json, src/assistantSdk/assistant.ts, src/assistantSdk/voice/voice.ts
<details>
<summary>📦 Published PR as canary version: <code>1.28.1--canary.164.6c15ab56e933b7661ecf1c1c41e3575a559ecae1.0</code></summary>
<br />
```bash
npm install @salutejs/client@1.28.1--canary.164.6c15ab56e933b7661ecf1c1c41e3575a559ecae1.0
yarn add @salutejs/client@1.28.1--canary.164.6c15ab56e933b7661ecf1c1c41e3575a559ecae1.0
```
</details>
=> test: Добавлены тесты на захват голоса

src/assistantSdk/assistant.ts
closes #48 
<details>
<summary>📦 Published PR as canary version: <code>1.29.0--canary.171.d688822097e436dc429376e6fe80390fab7fef38.0</code></summary>
<br />
```bash
npm install @salutejs/client@1.29.0--canary.171.d688822097e436dc429376e6fe80390fab7fef38.0
yarn add @salutejs/client@1.29.0--canary.171.d688822097e436dc429376e6fe80390fab7fef38.0
```
</details>
=> feat: Добавить mid в on('status')

cypress/integration/changeSettings.spec.ts, cypress/integration/dubbing.spec.ts, cypress/integration/resolveAudioContext.spec.ts, src/assistantSdk/client/client.ts
<details>
<summary>📦 Published PR as canary version: <code>1.28.1--canary.169.03cc7bfc05058b89d964d89106ed4093874cbcd7.0</code></summary>
<br />
```bash
npm install @salutejs/client@1.28.1--canary.169.03cc7bfc05058b89d964d89106ed4093874cbcd7.0
yarn add @salutejs/client@1.28.1--canary.169.03cc7bfc05058b89d964d89106ed4093874cbcd7.0
```
</details>
=> test: Добавлены тесты для озвучки

.github/workflows/release.yml, .lintstagedrc, cypress/integration/dubbing.spec.ts, cypress/integration/listen.spec.ts, src/assistantSdk/assistant.ts, src/assistantSdk/client/client.ts, src/assistantSdk/client/methods.ts, src/assistantSdk/client/protocol.ts, src/assistantSdk/meta.ts, src/assistantSdk/voice/recognizers/musicRecognizer.ts, src/assistantSdk/voice/recognizers/speechRecognizer.ts, src/assistantSdk/voice/voice.ts, src/index.ts, src/typings.ts
<details>
<summary>📦 Published PR as canary version: <code>1.30.0--canary.174.0f2dad8fcc16cd088fd5820eba65a6f75a4d3a75.0</code></summary>
<br />
```bash
npm install @salutejs/client@1.30.0--canary.174.0f2dad8fcc16cd088fd5820eba65a6f75a4d3a75.0
yarn add @salutejs/client@1.30.0--canary.174.0f2dad8fcc16cd088fd5820eba65a6f75a4d3a75.0
```
</details>
=> feat: стрим ответов

src/assistantSdk/assistant.ts, src/index.ts
<details>
<summary>📦 Published PR as canary version: <code>1.32.1--canary.177.56356ecf7437643a6b13f984f6f1dcc1b8013455.0</code></summary>
<br />
```bash
npm install @salutejs/client@1.32.1--canary.177.56356ecf7437643a6b13f984f6f1dcc1b8013455.0
yarn add @salutejs/client@1.32.1--canary.177.56356ecf7437643a6b13f984f6f1dcc1b8013455.0
```
</details>
=> Тип для параметров инициализации сдк

src/assistantSdk/voice/voice.ts
<details>
<summary>📦 Published PR as canary version: <code>1.32.2--canary.178.45ea3d373a25f8a2bcbb9ffeb117ced8a0d1f0c0.0</code></summary>
<br />
```bash
npm install @salutejs/client@1.32.2--canary.178.45ea3d373a25f8a2bcbb9ffeb117ced8a0d1f0c0.0
yarn add @salutejs/client@1.32.2--canary.178.45ea3d373a25f8a2bcbb9ffeb117ced8a0d1f0c0.0
```
</details>
=> fix: Ломается слушание после оффлайн

.github/workflows/save-bundle.yml
<details>
<summary>📦 Published PR as canary version: <code>1.32.3--canary.180.a090e390f412708aab25c9cec338c96025329fdf.0</code></summary>
<br />
```bash
npm install @salutejs/client@1.32.3--canary.180.a090e390f412708aab25c9cec338c96025329fdf.0
yarn add @salutejs/client@1.32.3--canary.180.a090e390f412708aab25c9cec338c96025329fdf.0
```
</details>
=> test: test

.github/workflows/bundle-report.yml
<details>
<summary>📦 Published PR as canary version: <code>1.32.3--canary.184.722180823c5633780f486a768cf00a511483d61c.0</code></summary>
<br />
```bash
npm install @salutejs/client@1.32.3--canary.184.722180823c5633780f486a768cf00a511483d61c.0
yarn add @salutejs/client@1.32.3--canary.184.722180823c5633780f486a768cf00a511483d61c.0
```
</details>
=> test: Bundle report test

src/createAssistantDevOrigin.ts
<details>
<summary>📦 Published PR as canary version: <code>1.32.3--canary.186.4085fc58bc0855bea202d10c64caa480542826e0.0</code></summary>
<br />
```bash
npm install @salutejs/client@1.32.3--canary.186.4085fc58bc0855bea202d10c64caa480542826e0.0
yarn add @salutejs/client@1.32.3--canary.186.4085fc58bc0855bea202d10c64caa480542826e0.0
```
</details>
=> адрес стенда для createSmartappDebugger

src/assistantSdk/client/protocol.ts, src/assistantSdk/client/transport.ts
<details>
<summary>📦 Published PR as canary version: <code>1.32.5--canary.193.ed9071cbcc5b1b6a5e606330dc5932eaa4d17046.0</code></summary>
<br />
```bash
npm install @salutejs/client@1.32.5--canary.193.ed9071cbcc5b1b6a5e606330dc5932eaa4d17046.0
yarn add @salutejs/client@1.32.5--canary.193.ed9071cbcc5b1b6a5e606330dc5932eaa4d17046.0
```
</details>
=> Не отправлять сообщения в сокет, если оффлайн

src/assistantSdk/assistant.ts
<details>
<summary>📦 Published PR as canary version: <code>1.32.7--canary.196.e064c77eab37624b85634ee9a8783c0f994ea4d8.0</code></summary>
<br />
```bash
npm install @salutejs/client@1.32.7--canary.196.e064c77eab37624b85634ee9a8783c0f994ea4d8.0
yarn add @salutejs/client@1.32.7--canary.196.e064c77eab37624b85634ee9a8783c0f994ea4d8.0
```
</details>
=> fix: исправлена сериализация строк в meta

package-lock.json, package.json
<details>
<summary>📦 Published PR as canary version: <code>1.32.8--canary.199.0f8a19bafea88fac0c354024d97a6a6f4736cfd5.0</code></summary>
<br />
```bash
npm install @salutejs/client@1.32.8--canary.199.0f8a19bafea88fac0c354024d97a6a6f4736cfd5.0
yarn add @salutejs/client@1.32.8--canary.199.0f8a19bafea88fac0c354024d97a6a6f4736cfd5.0
```
</details>
=> chore: bump autoit

src/assistantSdk/assistant.ts, src/assistantSdk/client/client.ts
<details>
<summary>📦 Published PR as canary version: <code>1.33.0--canary.200.0d97a08f4eb2c86c580c86a58a6ff211329e3ff7.0</code></summary>
<br />
```bash
npm install @salutejs/client@1.33.0--canary.200.0d97a08f4eb2c86c580c86a58a6ff211329e3ff7.0
yarn add @salutejs/client@1.33.0--canary.200.0d97a08f4eb2c86c580c86a58a6ff211329e3ff7.0
```
</details>
=> feat: передавать мету в первом чанке с голосом

src/assistantSdk/assistant.ts
<details>
<summary>📦 Published PR as canary version: <code>1.33.1--canary.201.0e3ee3f6717fbc9006d3097ee586ff04b875e5db.0</code></summary>
<br />
```bash
npm install @salutejs/client@1.33.1--canary.201.0e3ee3f6717fbc9006d3097ee586ff04b875e5db.0
yarn add @salutejs/client@1.33.1--canary.201.0e3ee3f6717fbc9006d3097ee586ff04b875e5db.0
```
</details>
=> fix: исправлена сериализация json-строк в meta

src/assistantSdk/voice/player/chunkQueue.ts, src/assistantSdk/voice/player/trackStream.ts
<details>
<summary>📦 Published PR as canary version: <code>1.33.3--canary.205.363215f68019c7b1ef381aadb3a4bd80b49d8891.0</code></summary>
<br />
```bash
npm install @salutejs/client@1.33.3--canary.205.363215f68019c7b1ef381aadb3a4bd80b49d8891.0
yarn add @salutejs/client@1.33.3--canary.205.363215f68019c7b1ef381aadb3a4bd80b49d8891.0
```
</details>
=> Лагание озвучки на android

package-lock.json, package.json, src/assistantSdk/voice/audioContext.ts, src/assistantSdk/voice/player/iosSilentModePatch.ts, src/assistantSdk/voice/voice.ts
closes #205 
<details>
<summary>📦 Published PR as canary version: <code>1.33.4--canary.209.cec69bb039cf96518ea20a5d4a5599cbac8bfc37.0</code></summary>
<br />
```bash
npm install @salutejs/client@1.33.4--canary.209.cec69bb039cf96518ea20a5d4a5599cbac8bfc37.0
yarn add @salutejs/client@1.33.4--canary.209.cec69bb039cf96518ea20a5d4a5599cbac8bfc37.0
```
</details>
=> fix: Не работает воспроизведение в silent mode ios 15

src/assistantSdk/assistant.ts, src/assistantSdk/voice/listener/navigatorAudioProvider.ts, src/assistantSdk/voice/listener/voiceListener.ts, src/assistantSdk/voice/voice.ts
<details>
<summary>📦 Published PR as canary version: <code>1.34.0--canary.212.a4e3076c4e9c7e989829653859826c3465318acf.0</code></summary>
<br />
```bash
npm install @salutejs/client@1.34.0--canary.212.a4e3076c4e9c7e989829653859826c3465318acf.0
yarn add @salutejs/client@1.34.0--canary.212.a4e3076c4e9c7e989829653859826c3465318acf.0
```
</details>
=> feat: Добавлено событие с данными аналайзера

src/assistantSdk/voice/player/iosSilentModePatch.ts
<details>
<summary>📦 Published PR as canary version: <code>1.33.7--canary.213.5d2ed5bf4dfa1640c64b640330b2b24325a1bb22.0</code></summary>
<br />
```bash
npm install @salutejs/client@1.33.7--canary.213.5d2ed5bf4dfa1640c64b640330b2b24325a1bb22.0
yarn add @salutejs/client@1.33.7--canary.213.5d2ed5bf4dfa1640c64b640330b2b24325a1bb22.0
```
</details>
=> fix: window navigator on server

src/typings.ts
<details>
<summary>📦 Published PR as canary version: <code>1.35.1--canary.217.5ed5010e84904346f94bcb46b8e38d665ea8dcf9.0</code></summary>
<br />
```bash
npm install @salutejs/client@1.35.1--canary.217.5ed5010e84904346f94bcb46b8e38d665ea8dcf9.0
yarn add @salutejs/client@1.35.1--canary.217.5ed5010e84904346f94bcb46b8e38d665ea8dcf9.0
```
</details>
=> fix: Экспорт SourceMeta

src/assistantSdk/assistant.ts, src/assistantSdk/voice/listener/navigatorAudioProvider.ts, src/assistantSdk/voice/voice.ts
<details>
<summary>📦 Published PR as canary version: <code>1.35.2--canary.218.bea68118713d601884e65a882fa9a3ed42a43030.0</code></summary>
<br />
```bash
npm install @salutejs/client@1.35.2--canary.218.bea68118713d601884e65a882fa9a3ed42a43030.0
yarn add @salutejs/client@1.35.2--canary.218.bea68118713d601884e65a882fa9a3ed42a43030.0
```
</details>
=> fix: Фикс analyser

README.md
<details>
<summary>📦 Published PR as canary version: <code>1.35.4--canary.221.c173c4c1fbdbf84392c6282a0df29dabed941d0e.0</code></summary>
<br />
```bash
npm install @salutejs/client@1.35.4--canary.221.c173c4c1fbdbf84392c6282a0df29dabed941d0e.0
yarn add @salutejs/client@1.35.4--canary.221.c173c4c1fbdbf84392c6282a0df29dabed941d0e.0
```
</details>
=> docs: актуальные ссылки в README.md

src/assistantSdk/voice/voice.ts
Обработка ошибок в случае отсутствия доступа к микрофону. Хоистится в глобальный скоуп
=> fix: add error handling for auto listening

src/assistantSdk/assistant.ts
<details>
<summary>📦 Published PR as canary version: <code>1.35.6--canary.227.6937ac504a69ebc2566f5211b81a6795ca38533a.0</code></summary>
<br />
```bash
npm install @salutejs/client@1.35.6--canary.227.6937ac504a69ebc2566f5211b81a6795ca38533a.0
yarn add @salutejs/client@1.35.6--canary.227.6937ac504a69ebc2566f5211b81a6795ca38533a.0
```
</details>
=> fix: сериализация строк для meta

src/assistantSdk/assistant.ts
<details>
<summary>📦 Published PR as canary version: <code>1.35.7--canary.229.471ab66f03055914fd68213240e0023f29a8f743.0</code></summary>
<br />
```bash
npm install @salutejs/client@1.35.7--canary.229.471ab66f03055914fd68213240e0023f29a8f743.0
yarn add @salutejs/client@1.35.7--canary.229.471ab66f03055914fd68213240e0023f29a8f743.0
```
</details>
=> fix: Откат фикса сериализации

src/assistantSdk/voice/player/trackStream.ts
Решены две проблемы:
1. Для аудио короче 1 секунды вопроизведение не запускается совсем, т.к. буфер не наполняется, а проверка флага `loaded` и `queue.ended` выполняются раньше чем выполняется добавление чанка из буфера в очередь
2. Возможна ситуация, когда для `source` срабатывает `onended`, при этом в буфере ещё есть данные и последний чанк (с флагом last=1) не получен. Это вызывает преждевременно прерывание воспроизведение.
fixes #232
=> Исправить вопроизведение коротких tts аудио

rollup.config.js, src/index.ts
<details>
<summary>📦 Published PR as canary version: <code>1.35.10--canary.234.bea9ededcdb2d44346e7f14f97491ec4549c6048.0</code></summary>
<br />
```bash
npm install @salutejs/client@1.35.10--canary.234.bea9ededcdb2d44346e7f14f97491ec4549c6048.0
yarn add @salutejs/client@1.35.10--canary.234.bea9ededcdb2d44346e7f14f97491ec4549c6048.0
```
</details>
=> fix: экспорт транспорта из пакета

rollup.config.js, src/assistantSdk/assistant.ts, src/assistantSdk/client/pureClient.ts, src/assistantSdk/const.ts, src/assistantSdk/utils.ts, src/assistantSdk/voice/listener/navigatorAudioProvider.ts, src/assistantSdk/voice/player/trackStream.ts, src/assistantSdk/voice/player/utils.ts, src/index.ts
<details>
<summary>📦 Published PR as canary version: <code>1.36.0--canary.235.421d3381b1ad2e910040fd1c0baaff346be41088.0</code></summary>
<br />
```bash
npm install @salutejs/client@1.36.0--canary.235.421d3381b1ad2e910040fd1c0baaff346be41088.0
yarn add @salutejs/client@1.36.0--canary.235.421d3381b1ad2e910040fd1c0baaff346be41088.0
```
</details>
=> feat: Добавлен флаг echoCancellation для AudioProvider
